### PR TITLE
Release pipelines should not fail if they dont have containerd dependencies provided

### PR DESCRIPTION
**Pull request by xtreme-sameer-vohra**
# dev-image Job
Addresses broken pre-v6 releases pipelines [dev-image job](https://ci.concourse-ci.org/teams/main/pipelines/release-5.8.x/jobs/dev-image/builds/14)
```
 > [7/18] COPY runc/runc.amd64 /usr/local/concourse/bin/runc:
------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/runc/runc.amd64" not found: not found
FATA[0016] failed to build: build: exit status 1        
FATA[0016] failed to run task: exit status 1   
```
The dev image needs to package containerd and its dependencies for v6 dev.
  However, it isn't required for v5 releases and therefore we'd
  want to avoid bundling it in unnecessarily.

  There doesn't appear to be an clean way to make containerd reqs
  optional in the Dockerfile. Tried using the `ONBUILD` directive with the `FROM` clause, however got this error
```
initializing
fetching concourse/builder@sha256:b9d526e9608ebbbb7da85128ece2c166f080c8d566450f3b9ce2d3c0bd56498e
4fe2ade4980c [==========================================] 2.1MiB/2.1MiB
4658739bada1 [==========================================] 9.6MiB/9.6MiB
010d9d7aa315 [==========================================] 8.1MiB/8.1MiB
8ed4b443c253 [==========================================] 2.5MiB/2.5MiB
8d4eb7fd18e8 [==========================================] 1.5KiB/1.5KiB
3a8ae002788a [==========================================] 1.5MiB/1.5MiB
640b3c9e8cf3 [==========================================] 1.1KiB/1.1KiB
running build
building
Building docker.io/concourse/dev:latest
Setting up the rootfs... this may take a bit.
[+] Building 0.1s (2/2) FINISHED
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load Dockerfile                                             0.0s
 => => transferring dockerfile: 3.19kB                                     0.0s
failed to solve: failed to create LLB definition: invalid reference format
failed
```

similar to [this](https://github.com/moby/buildkit/issues/717)

  The Dockerfile-v5 doesn't include containerd dependencies.
  The Dockerfile-v5 can be dropped when no v5 releases are in support.

# build-rc Job
Parametrized installing containerd and its dependencies based on the major version of Concourse being greater than 5. This way the dependencies won't be installed for v5 releases.

### CODE REVIEW

**Comment by pivotal-jamie-klassen** [comment]
Just checking - are you aware of the WIP by @muntac and @jomsie on #293? This looks very similar, and while I think it's a good solution, you are likely to encounter further containerd-related pain as you iterate on what I assume is the `release/5.8.x` pipeline.

**Comment by xtreme-sameer-vohra** [comment]
> #293

wow, thanks, i had not done the right thing of looking through issues prior to delving into this

**Comment by cirocosta** [comment]
> There doesn't appear to be an clean way to make containerd reqs
optional in the Dockerfile. 

oh, I think there's a way - we could leverage build args and then conditionally pick the target we want to achieve through the build process.

I'll sketch an example

**Comment by cirocosta** [comment]
@xtreme-sameer-vohra I didn't really test this one out (given all of the inputs and stuff that the task requires :sweat: ), but something like the following:

```dockerfile
ARG runtime="gdn"

FROM scratch AS gdn-deps

	COPY gdn/gdn-* /usr/local/concourse/bin/gdn


FROM scratch AS containerd-deps

	ADD containerd/containerd-*.linux-amd64.tar.gz /usr/local/concourse
	COPY runc/runc.amd64 /usr/local/concourse/bin/runc
	ADD cni/cni-plugins-linux-amd64-*.tgz /usr/local/concourse/bin


FROM ${runtime}-deps AS deps

FROM scratch AS fly

	COPY fly-linux/fly-*.tgz /usr/local/concourse/fly-assets
	COPY fly-windows/fly-*.zip /usr/local/concourse/fly-assets
	COPY fly-darwin/fly-*.tgz /usr/local/concourse/fly-assets
	

FROM concourse/golang-builder AS concourse

	RUN apt-get update && apt-get -y install \
	      btrfs-tools \
	      ca-certificates \
	      file \
	      iproute2 \
	      iptables \
	      tree

	RUN mkdir /usr/local/concourse/fly-assets

	COPY concourse /src

	RUN  set -x && \
		gcc -O2 -static -o /usr/local/concourse/bin/init /src/cmd/init/init.c

	RUN cd /src && \
	      go mod download && \
	      go install github.com/gobuffalo/packr/packr && \
	      packr build -gcflags=all="-N -l" -o /usr/local/concourse/bin/concourse \
		./cmd/concourse && \
	      rm -rf /src


FROM concourse/golang-builder AS release

	RUN apt-get update && apt-get -y install \
	      btrfs-tools \
	      ca-certificates \
	      dumb-init \
	      file \
	      iproute2 \
	      iptables

	VOLUME /worker-state
	ENV CONCOURSE_WORK_DIR /worker-state

	ENV CONCOURSE_GARDEN_DNS_PROXY_ENABLE true
	ENV CONCOURSE_SESSION_SIGNING_KEY     /concourse-keys/session_signing_key
	ENV CONCOURSE_TSA_AUTHORIZED_KEYS     /concourse-keys/authorized_worker_keys
	ENV CONCOURSE_TSA_HOST_KEY            /concourse-keys/tsa_host_key
	ENV CONCOURSE_TSA_PUBLIC_KEY          /concourse-keys/tsa_host_key.pub
	ENV CONCOURSE_TSA_WORKER_PRIVATE_KEY  /concourse-keys/worker_key
	ENV PATH /usr/local/concourse/bin:${PATH}
	ENV CONTAINERD_NAMESPACE=concourse


	COPY ./resource-types-image/rootfs/usr/local/concourse/resource-types/ /usr/local/concourse/resource-types/

	COPY --from=deps /usr/local/concourse/bin
	COPY --from=fly /usr/local/concourse/bin
	COPY --from=concourse /usr/local/concourse/bin

	RUN chmod -R +x /usr/local/concourse/bin

	ENTRYPOINT ["dumb-init", "concourse"]
```

with `docker build -t myimage --build-arg runtime=gdn` would not include the containerd stuff, and a ``docker build -t myimage --build-arg runtime=gdn` would (we could have an `all` or something like that that includes all for `6.0`)

**Comment by pivotal-jamie-klassen** [comment]
@cirocosta that is very cool! I had thought of a way to use multiple Dockerfiles, but this is a nice single-Dockerfile solution

**Pull request merged**
