### PR TITLE
Revert "temp freezing registry-image-resource to 0.8.0 for concourse.…

### PR DESCRIPTION
**Pull request by xtreme-sameer-vohra**
Remove the temp change freezing the registry-image-resource

Determined that freezing the image didn't resolve the issue and we continued seeing 429 errors.

Signed-off-by: Sameer Vohra <svohra@pivotal.io>

### CODE REVIEW

**Comment by cirocosta** [comment]
@xtreme-sameer-vohra do we still need this?

@taylorsilva  is this required for 5.7.1? 🤔  

thanks!

**Comment by taylorsilva** [comment]
5.7.1 was already unpinned, using `0.8.1`

**Comment by xtreme-sameer-vohra** [comment]
@cirocosta Yes, this was meant for as a temporary workaround to see if it reduce the impact of the Docker change. Once we validated it did not have a change, we'd like our pipeline to leverage the latest version of the resource.

**Comment by xtreme-sameer-vohra** [comment]
thx for the review @pivotal-jamie-klassen

**Pull request merged**
